cimport quantlib._defines as _def

QL_MIN_INTEGER = _def.QL_MIN_INTEGER
QL_MAX_INTEGER = _def.QL_MAX_INTEGER
QL_MIN_REAL = _def.QL_MIN_REAL
QL_MAX_REAL = _def.QL_MAX_REAL
QL_MIN_POSITIVE_REAL = _def.QL_MIN_POSITIVE_REAL
QL_EPSILON = _def.QL_EPSILON
QL_NULL_INTEGER = _def.QL_NULL_INTEGER
QL_NULL_REAL = _def.QL_NULL_REAL
